name: fismatik
description: "FişMatik Gider Takip Uygulaması"
publish_to: 'none'
version: 1.0.1+94

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  shimmer: ^3.0.0
  timeago: ^3.6.1
  ntp: ^2.0.0
  flutter_dotenv: ^6.0.0
  provider: ^6.0.0
  flutter_local_notifications: ^19.5.0
  flutter_timezone: ^5.0.1
  timezone: ^0.10.1
  supabase_flutter: ^2.8.0
  google_mobile_ads: ^5.3.1
  google_sign_in: ^7.2.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  uuid: ^4.0.0
  intl: ^0.20.2
  pdf: ^3.10.0
  printing: ^5.11.0
  path_provider: ^2.1.0
  open_file: ^3.3.0
  image_picker: ^1.1.0
  google_mlkit_text_recognition: ^0.15.0
  permission_handler: ^11.4.0
  google_fonts: ^6.2.0
  fl_chart: ^1.1.1
  excel: ^4.0.0
  share_plus: ^12.0.1
  in_app_purchase: ^3.2.0
  table_calendar: ^3.1.0
  url_launcher: ^6.3.2
  lottie: ^3.1.2
  home_widget: ^0.8.1
  telephony: ^0.2.0
  universal_html: ^2.3.0
  universal_io: ^2.2.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/favicon.png"
  min_sdk_android: 21