name: fismatik
description: "FişMatik Gider Takip Uygulaması"
publish_to: 'none'
version: 1.0.0+20

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  shimmer: ^3.0.0
  timeago: ^3.6.1
  ntp: ^2.0.0
  flutter_dotenv: ^5.1.0
  provider: ^6.0.0
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^3.0.0
  timezone: ^0.9.0
  local_auth: ^2.2.0
  supabase_flutter: ^2.5.0
  google_mobile_ads: ^5.1.0
  google_sign_in: ^6.1.0
  uuid: ^4.0.0
  intl: ^0.20.2
  pdf: ^3.10.0
  printing: ^5.11.0
  path_provider: ^2.1.0
  open_file: ^3.3.0
  image_picker: ^1.0.0
  google_mlkit_text_recognition: ^0.11.0
  permission_handler: ^11.0.0
  google_fonts: ^6.2.0
  fl_chart: ^0.66.0
  excel: ^4.0.0
  share_plus: ^10.0.0
  in_app_purchase: ^3.2.0
  table_calendar: ^3.1.0
  url_launcher: ^6.3.2
  lottie: ^3.1.2
  home_widget: ^0.8.1
  universal_html: ^2.3.0
  universal_io: ^2.2.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21